services:
  web:
    build: . # build context where my docker files are present . means current directory
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: 'true'
  redis:
    image: "redis:alpine"
